import json
import time
from pathlib import Path

from parser.build_graph import build_graph, export_graph

from summarizer.summarize_file import (
    summarize_file,
    save_summary,
)

from summarizer.summarize_module import (
    summarize_module,
    save_module_summary,
)

from graph.enrich_graph import (
    enrich_and_save,
    enrich_module_and_save,
    save_file_enrichment_report,
    save_module_enrichment_report,
)


# ============================================================
# CONFIG
# ============================================================

REPO_ROOT = Path(
    "test_repo/flask/src/flask"
)

MAX_RETRIES = 2


# ============================================================
# FILE DISCOVERY
# ============================================================

def discover_files():
    """
    Find all Python source files in the target repository.
    """

    return sorted(
        file
        for file in REPO_ROOT.rglob("*.py")
        if "__pycache__" not in file.parts
    )


# ============================================================
# GRAPH INITIALIZATION
# ============================================================

def initialize_graph():
    """
    Build the structural knowledge graph before
    semantic enrichment begins.
    """

    print(
        "[FUSE] Building structural knowledge graph..."
    )

    graph = build_graph(
        REPO_ROOT
    )

    export_graph(
        graph
    )

    print(
        f"[FUSE] Structural graph ready: "
        f"{graph.number_of_nodes()} nodes, "
        f"{graph.number_of_edges()} edges"
    )

    return graph


# ============================================================
# SYMBOL EXTRACTION
# ============================================================

def get_file_symbols(
    graph,
    file_path: Path,
):
    """
    Extract the exact symbols generated by Tree-sitter
    for one file.

    These symbols are passed to Gemini so Gemini only
    describes symbols that actually exist in the graph.
    """

    relative_path = str(
        file_path.relative_to(
            REPO_ROOT
        )
    )

    symbols = []

    for node_id, data in graph.nodes(
        data=True
    ):

        node_type = data.get(
            "type"
        )

        if node_type not in {
            "class",
            "function",
            "method",
        }:
            continue

        if data.get("file") != relative_path:
            continue

        symbols.append({
            "name": data.get("name"),
            "type": node_type,
            "parent": data.get(
                "parent",
                "",
            ),
            "line": data.get("line"),
            "end_line": data.get(
                "end_line"
            ),
        })

    return symbols


# ============================================================
# FILE SUMMARIZATION
# LEVEL 2 + LEVEL 3
# ============================================================

def process_file(
    file_path: Path,
    index: int,
    total: int,
    graph,
):
    """
    Generate Level 2 file summary and Level 3 symbol
    descriptions, then enrich the graph.
    """

    relative_path = file_path.relative_to(
        REPO_ROOT
    )

    print(
        f"[{index}/{total}] "
        f"Gemini → {relative_path}",
        end=" ",
        flush=True,
    )

    # --------------------------------------------------------
    # TREE-SITTER SYMBOLS
    # --------------------------------------------------------

    symbols = get_file_symbols(
        graph,
        file_path,
    )

    last_error = None

    # --------------------------------------------------------
    # RETRY
    # --------------------------------------------------------

    for attempt in range(
        1,
        MAX_RETRIES + 1,
    ):

        try:

            # ------------------------------------------------
            # GEMINI — LEVEL 2 + LEVEL 3
            # ------------------------------------------------

            result = summarize_file(
                file_path,
                symbols,
            )

            # ------------------------------------------------
            # SAVE FILE/SYMBOL SUMMARY
            # ------------------------------------------------

            save_summary(
                file_path,
                result,
            )

            # ------------------------------------------------
            # ENRICH FILE + SYMBOL NODES
            # ------------------------------------------------

            enrichment = enrich_and_save(
                str(relative_path),
                result,
            )

            # ------------------------------------------------
            # SAVE REPORT
            # ------------------------------------------------

            save_file_enrichment_report(
                str(relative_path),
                enrichment,
            )

            enriched = len(
                enrichment.get(
                    "enriched",
                    [],
                )
            )

            missed = len(
                enrichment.get(
                    "missed",
                    [],
                )
            )

            print(
                f"✓ "
                f"({enriched} enriched"
                f", {missed} missed)"
            )

            return {
                "status": "success",
                "file": str(
                    relative_path
                ),
                "enriched": enriched,
                "missed": missed,
                "attempts": attempt,
            }

        except Exception as error:

            last_error = error

            if attempt < MAX_RETRIES:

                print(
                    f"retry {attempt}...",
                    end=" ",
                    flush=True,
                )

                time.sleep(2)

            else:

                print(
                    f"✗ FAILED: {error}"
                )

    return {
        "status": "failed",
        "file": str(
            relative_path
        ),
        "error": str(
            last_error
        ),
        "attempts": MAX_RETRIES,
    }


# ============================================================
# MODULE DISCOVERY
# ============================================================

def get_modules(
    graph,
):
    """
    Return all module nodes from the structural graph.
    """

    modules = []

    for node_id, data in graph.nodes(
        data=True
    ):

        if data.get("type") != "module":
            continue

        modules.append(
            data.get("name")
        )

    return sorted(
        module
        for module in modules
        if module
    )


# ============================================================
# FILE SUMMARIES FOR MODULE
# ============================================================

def get_module_file_summaries(
    graph,
    module_name,
    summaries,
):
    """
    Collect the already-generated Level 2 file summaries
    belonging to one module.
    """

    file_summaries = []

    for node_id, data in graph.nodes(
        data=True
    ):

        if data.get("type") != "file":
            continue

        if data.get("module") != module_name:
            continue

        file_path = data.get(
            "path"
        )

        if file_path not in summaries:
            continue

        file_summary = summaries[
            file_path
        ]

        file_summaries.append({
            "path": file_path,
            "summary": file_summary.get(
                "file_summary",
                "",
            ),
        })

    return file_summaries


# ============================================================
# MODULE SUMMARIZATION
# LEVEL 1
# ============================================================

def process_module(
    module_name,
    file_summaries,
    index,
    total,
):
    """
    Generate a Level 1 module summary from the
    already-generated Level 2 file summaries.
    """

    print(
        f"[{index}/{total}] "
        f"Gemini → module:{module_name}",
        end=" ",
        flush=True,
    )

    last_error = None

    for attempt in range(
        1,
        MAX_RETRIES + 1,
    ):

        try:

            # ------------------------------------------------
            # GEMINI — LEVEL 1
            # ------------------------------------------------

            result = summarize_module(
                module_name,
                file_summaries,
            )

            # ------------------------------------------------
            # SAVE MODULE SUMMARY
            # ------------------------------------------------

            save_module_summary(
                module_name,
                result,
            )

            # ------------------------------------------------
            # ENRICH MODULE NODE
            # ------------------------------------------------

            enrichment = enrich_module_and_save(
                module_name,
                result,
            )

            # ------------------------------------------------
            # SAVE REPORT
            # ------------------------------------------------

            save_module_enrichment_report(
                module_name,
                enrichment,
            )

            enriched = len(
                enrichment.get(
                    "enriched",
                    [],
                )
            )

            missed = len(
                enrichment.get(
                    "missed",
                    [],
                )
            )

            print(
                f"✓ "
                f"({enriched} enriched"
                f", {missed} missed)"
            )

            return {
                "status": "success",
                "module": module_name,
                "enriched": enriched,
                "missed": missed,
                "attempts": attempt,
            }

        except Exception as error:

            last_error = error

            if attempt < MAX_RETRIES:

                print(
                    f"retry {attempt}...",
                    end=" ",
                    flush=True,
                )

                time.sleep(2)

            else:

                print(
                    f"✗ FAILED: {error}"
                )

    return {
        "status": "failed",
        "module": module_name,
        "error": str(
            last_error
        ),
        "attempts": MAX_RETRIES,
    }


# ============================================================
# LOAD FILE SUMMARIES
# ============================================================

def load_file_summaries():
    """
    Load the Level 2 file summaries generated during
    the first semantic enrichment stage.
    """

    summary_file = Path(
        "data/summaries.json"
    )

    if not summary_file.exists():
        raise RuntimeError(
            "data/summaries.json was not generated."
        )

    with summary_file.open(
        "r",
        encoding="utf-8",
    ) as f:

        return json.load(f)


# ============================================================
# MODULE ENRICHMENT
# ============================================================

def enrich_modules(
    graph,
):
    """
    Generate Level 1 module summaries after all
    Level 2 file summaries are available.
    """

    print()
    print(
        "[FUSE] Starting module-level semantic enrichment..."
    )

    summaries = load_file_summaries()

    modules = get_modules(
        graph
    )

    print(
        f"[FUSE] Found {len(modules)} modules"
    )

    results = []

    for index, module_name in enumerate(
        modules,
        start=1,
    ):

        file_summaries = get_module_file_summaries(
            graph,
            module_name,
            summaries,
        )

        if not file_summaries:

            print(
                f"[{index}/{len(modules)}] "
                f"module:{module_name} "
                "✗ NO FILE SUMMARIES"
            )

            results.append({
                "status": "failed",
                "module": module_name,
                "error": (
                    "No Level 2 file summaries "
                    "found for module."
                ),
            })

            continue

        result = process_module(
            module_name,
            file_summaries,
            index,
            len(modules),
        )

        results.append(
            result
        )

    return results


# ============================================================
# ORCHESTRATOR
# ============================================================

def run():

    print("=" * 60)
    print(
        "FUSE — CODEBASE KNOWLEDGE GRAPH BUILDER"
    )
    print("=" * 60)

    # --------------------------------------------------------
    # 1. DISCOVER REPOSITORY
    # --------------------------------------------------------

    files = discover_files()

    print(
        f"[FUSE] Found {len(files)} Python files"
    )

    if not files:

        raise RuntimeError(
            f"No Python files found in {REPO_ROOT}"
        )

    print()

    # --------------------------------------------------------
    # 2. BUILD STRUCTURAL GRAPH
    # --------------------------------------------------------

    graph = initialize_graph()

    print()

    # --------------------------------------------------------
    # 3. LEVEL 2 + LEVEL 3
    # --------------------------------------------------------

    print(
        "[FUSE] Starting file/symbol semantic enrichment..."
    )

    start_time = time.time()

    file_results = []

    for index, file_path in enumerate(
        files,
        start=1,
    ):

        result = process_file(
            file_path,
            index,
            len(files),
            graph,
        )

        file_results.append(
            result
        )

    # --------------------------------------------------------
    # 4. LEVEL 1
    # --------------------------------------------------------

    module_results = enrich_modules(
        graph
    )

    elapsed = (
        time.time()
        - start_time
    )

    # --------------------------------------------------------
    # 5. FINAL REPORT
    # --------------------------------------------------------

    successful_files = [
        result
        for result in file_results
        if result["status"] == "success"
    ]

    failed_files = [
        result
        for result in file_results
        if result["status"] == "failed"
    ]

    successful_modules = [
        result
        for result in module_results
        if result["status"] == "success"
    ]

    failed_modules = [
        result
        for result in module_results
        if result["status"] == "failed"
    ]

    total_file_enriched = sum(
        result.get(
            "enriched",
            0,
        )
        for result in successful_files
    )

    total_file_missed = sum(
        result.get(
            "missed",
            0,
        )
        for result in successful_files
    )

    total_module_enriched = sum(
        result.get(
            "enriched",
            0,
        )
        for result in successful_modules
    )

    total_module_missed = sum(
        result.get(
            "missed",
            0,
        )
        for result in successful_modules
    )

    print()
    print("=" * 60)
    print(
        "FUSE COMPLETE"
    )
    print("=" * 60)

    print(
        f"Files discovered       : {len(files)}"
    )

    print(
        f"Files processed        : "
        f"{len(successful_files)}"
    )

    print(
        f"Files failed           : "
        f"{len(failed_files)}"
    )

    print(
        f"Modules processed      : "
        f"{len(successful_modules)}"
    )

    print(
        f"Modules failed         : "
        f"{len(failed_modules)}"
    )

    print(
        f"File/symbol enriched   : "
        f"{total_file_enriched}"
    )

    print(
        f"File/symbol missed     : "
        f"{total_file_missed}"
    )

    print(
        f"Module nodes enriched  : "
        f"{total_module_enriched}"
    )

    print(
        f"Module nodes missed    : "
        f"{total_module_missed}"
    )

    print(
        f"Time                   : "
        f"{elapsed:.1f}s"
    )

    print()
    print(
        "Output:"
    )

    print(
        "  data/code_graph.json"
    )

    print(
        "  data/enriched_code_graph.json"
    )

    print(
        "  data/summaries.json"
    )

    print(
        "  data/module_summaries.json"
    )

    print(
        "  data/enrichment_report.json"
    )

    # --------------------------------------------------------
    # FAILED FILES
    # --------------------------------------------------------

    if failed_files:

        print()
        print(
            "Failed files:"
        )

        for result in failed_files:

            print(
                f"  ✗ {result['file']}"
            )

            print(
                f"    {result['error']}"
            )

    # --------------------------------------------------------
    # FAILED MODULES
    # --------------------------------------------------------

    if failed_modules:

        print()
        print(
            "Failed modules:"
        )

        for result in failed_modules:

            print(
                f"  ✗ {result['module']}"
            )

            print(
                f"    {result['error']}"
            )


# ============================================================
# ENTRY POINT
# ============================================================

if __name__ == "__main__":
    run()